//! The menubar gauge: the tightest quota, rendered as an arc on the tray icon.
//!
//! Assets are generated by `desktop/icons-src/gen-tray-icons.py` and embedded,
//! so the binary carries its own icons and there is nothing to resolve at
//! runtime. They are macOS template images — alpha only, the system supplies
//! the colour to match the menubar.

use tauri::image::Image;

/// Fill levels we ship an icon for. A menubar glyph that moves on every poll is
/// noise, and nobody reads 63% off an 18pt arc, so readings are floored into
/// these. Must stay in step with BUCKETS in the generator.
const BUCKETS: [(u8, &[u8]); 5] = [
    (0, include_bytes!("../icons/tray/gauge-0.png")),
    (25, include_bytes!("../icons/tray/gauge-25.png")),
    (50, include_bytes!("../icons/tray/gauge-50.png")),
    (75, include_bytes!("../icons/tray/gauge-75.png")),
    (100, include_bytes!("../icons/tray/gauge-100.png")),
];

/// Shown when the server cannot be reached. Deliberately not the 0% gauge: a
/// full-but-empty ring would claim the quota is untouched, when the truth is
/// that we have no reading at all.
const OFFLINE: &[u8] = include_bytes!("../icons/tray/gauge-offline.png");

/// The highest live quota, as a percentage — "how close is the nearest wall".
///
/// Expired entries describe a window that has already rolled over, so their
/// number is stale and including it would keep a spent window on the menubar.
pub fn tightest_percent(quotas: &[serde_json::Value]) -> Option<f64> {
    quotas
        .iter()
        .filter(|q| !q.get("expired").and_then(|e| e.as_bool()).unwrap_or(false))
        .filter_map(|q| q.get("used_percent").and_then(|p| p.as_f64()))
        .fold(None, |acc: Option<f64>, p| {
            Some(acc.map_or(p, |a| a.max(p)))
        })
}

/// Floor a percentage to the bucket we have an icon for.
pub fn bucket_for(percent: f64) -> u8 {
    let mut chosen = BUCKETS[0].0;
    for (level, _) in BUCKETS {
        if percent >= level as f64 {
            chosen = level;
        }
    }
    chosen
}

/// The icon for a reading, or the offline glyph when there is none.
pub fn icon(percent: Option<f64>) -> tauri::Result<Image<'static>> {
    let bytes = match percent {
        None => OFFLINE,
        Some(p) => {
            let want = bucket_for(p);
            BUCKETS
                .iter()
                .find(|(level, _)| *level == want)
                .map(|(_, bytes)| *bytes)
                .unwrap_or(OFFLINE)
        }
    };
    Image::from_bytes(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn floors_into_buckets() {
        assert_eq!(bucket_for(0.0), 0);
        assert_eq!(bucket_for(24.9), 0);
        assert_eq!(bucket_for(25.0), 25);
        assert_eq!(bucket_for(74.9), 50);
        assert_eq!(bucket_for(99.9), 75);
        assert_eq!(bucket_for(100.0), 100);
    }

    // Over-limit readings are real: authoritative quota can report past 100.
    #[test]
    fn clamps_above_full() {
        assert_eq!(bucket_for(140.0), 100);
    }

    #[test]
    fn takes_the_highest_live_quota() {
        let quotas = vec![
            json!({"used_percent": 6.0, "expired": false}),
            json!({"used_percent": 51.0, "expired": false}),
            json!({"used_percent": 23.0}),
        ];
        assert_eq!(tightest_percent(&quotas), Some(51.0));
    }

    // A rolled-over window's number is stale; letting it win would pin the
    // menubar to a quota that no longer applies.
    #[test]
    fn ignores_expired_quotas() {
        let quotas = vec![
            json!({"used_percent": 99.0, "expired": true}),
            json!({"used_percent": 12.0, "expired": false}),
        ];
        assert_eq!(tightest_percent(&quotas), Some(12.0));
    }

    #[test]
    fn no_quotas_means_no_reading() {
        assert_eq!(tightest_percent(&[]), None);
        assert_eq!(
            tightest_percent(&[json!({"used_percent": 5.0, "expired": true})]),
            None
        );
    }

    #[test]
    fn every_bucket_asset_decodes() {
        for (level, _) in BUCKETS {
            icon(Some(level as f64))
                .unwrap_or_else(|e| panic!("bucket {level} icon failed to decode: {e}"));
        }
        icon(None).expect("offline icon failed to decode");
    }
}
